### ISSUE TITLE
Use external_volumes resource pararmeter to map storage items to right home and cache

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#127]
Define a plugin parameter like

![portal live surfresearchcloud nl_ (1)](https://user-images.githubusercontent.com/1713488/153868342-28fc90cf-fc9f-4397-be25-90c56897ada6.png)

In Ansible a external_volumes variable will be available which is a string. This contains the storage items in the order the user selected it.

To get /home and /dcache-cache mounted from the right storage items we need to map the volume_id to a disk id.
For example first volume_id is ddc30b53-105e-4113-9379-c7d3ec9d90e5 then /dev/sdb1 is the first storage item selected.
```
/dev/disk/by-id/
lrwxrwxrwx 1 root root  9 Jan  6 15:09 scsi-SQEMU_QEMU_HARDDISK_ddc30b53-105e-4113-9379-c7d3ec9d90e5 -> ../../sdb
lrwxrwxrwx 1 root root 10 Jan  6 15:09 scsi-SQEMU_QEMU_HARDDISK_ddc30b53-105e-4113-9379-c7d3ec9d90e5-part1 -> ../../sdb1
```

**Comment by sverhoeven** [comment]
Ansible tasks could be something like

```yaml
shell: echo {{ external_volumes }} | jq [0].volume_id | <grep in /dev/disk/by-id/ for right sdXX>
  register: home_device
mount:
  src: home_device
  target: home_dir
```
